<?php

$ANCHOCARPETA = '180';
$ALTOCARPETA = '150';
$FOTOSANCHO = '1';
$FOTOSALTO = '4';
$PERMITIRENVIARFICHEROS = '1';
$PERMITIRENVIARCOMENTARIOS = '1';
$PERMITIRENVIARVOTACIONES = '1';
$KBDOWNLOADERIAHEADERSTART = '<H1>';
$KBDOWNLOADERYAHEADEREND = '</H1>';
$KBDOWNLOADERIAFOOTSTART = '<H3>';
$KBDOWNLOADERYAFOOTEND = '</H3>';
$KBDOWNLOADERYAPREVIOUS = 'Anterior';
$KBDOWNLOADERYANEXT = 'Próximo';
$COLORENCABEZADOCOMENTARIO = '';
$COLORCOMENTARIO = '';
